services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_DSN: "postgres://postgres:postgres@db:5432/calendar_db?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      PG_DSN: "postgres://postgres:postgres@db:5432/calendar_db?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    command: go test -v ./tests/integration/...

volumes:
  postgres_data: 